import fs from 'node:fs';import path from 'node:path';import {projects,team,services,studioPhoto} from './data.mjs';
const out='dist';fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync('public',out,{recursive:true});
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=id=>`/assets/${id}.webp`;
const header=active=>`<a class="skip" href="#main">Saltar al contenido</a><header class="site-header"><a class="brand" href="/" aria-label="Pipitik, inicio"><img src="/assets/logo.webp" alt="Pipitik" width="200" height="82"></a><button class="menu-toggle" aria-label="Abrir menú" aria-expanded="false" aria-controls="navigation"><span></span><span></span></button><nav id="navigation" aria-label="Navegación principal"><a href="/equipo/" ${active==='equipo'?'aria-current="page"':''}>El taller</a><a href="/proyectos/" ${active==='proyectos'?'aria-current="page"':''}>Proyectos</a><a href="/#servicios">Servicios</a><a href="#contacto">Contacto</a></nav></header>`;
const footer=`<footer><a class="brand" href="/" aria-label="Pipitik, inicio"><img src="/assets/logo.webp" alt="Pipitik" width="180" height="75"></a><div><nav aria-label="Pie de página"><a href="/equipo/">El taller</a><a href="/proyectos/">Proyectos</a><a href="#contacto">Contacto</a></nav><p>Pipitik © ${new Date().getFullYear()} · Taller de escultura</p></div></footer>`;
const contact=`<section class="contact" id="contacto"><div class="wrap"><p class="eyebrow">De la idea a la realidad</p><h2>¿QUÉ VAMOS<br>A CREAR?</h2><p>Cuéntanos tu idea. Hagámosla realidad.</p><div class="contact-actions"><a class="button dark" href="mailto:pipitikgroup@hotmail.com?subject=Proyecto%20para%20Pipitik">Hablemos de tu proyecto</a><a class="contact-whatsapp" href="https://wa.me/525527233920" target="_blank" rel="noopener">Escríbenos por WhatsApp</a></div></div></section>`;
const dialog=`<dialog class="lightbox" aria-label="Fotografía del proyecto"><button class="lightbox-close" aria-label="Cerrar fotografía">Cerrar ×</button><img alt=""><p></p></dialog>`;
const page=(title,description,route,content,active='',image=projects[0].hero)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · Pipitik</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#111111"><link rel="icon" href="/assets/favicon.svg"><link rel="canonical" href="https://pipitik.netlify.app${route}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)} · Pipitik"><meta property="og:description" content="${escape(description)}"><meta property="og:image" content="https://pipitik.netlify.app${image}"><meta property="og:url" content="https://pipitik.netlify.app${route}"><link rel="preload" href="/assets/anton.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/styles.css"><script src="/app.js" defer></script></head><body>${header(active)}<main id="main">${content}</main>${footer}${dialog}</body></html>`;
const label=(n,text)=>`<p class="section-label"><span>${n} / ${text}</span></p>`;
const card=(p,i)=>`<a class="project-card" href="/proyectos/${p.slug}/"><div class="card-image${p.fit==='contain'?' card-image-full':''}"><img src="${p.hero}" alt="${p.title}, pieza realizada por Pipitik" width="800" height="900" loading="lazy" style="object-position:${p.position||'50% 50%'}"><span class="card-number">${String(i+1).padStart(2,'0')}</span><span class="card-view">Ver proyecto</span></div><div class="card-copy"><h3>${p.short||p.title}</h3><p>${p.category}</p></div></a>`;
const home=`<section class="hero" style="--cover-image:url('${studioPhoto}')"><div class="hero-photo-frame"><img class="hero-photo" src="${studioPhoto}" alt="Equipo de Pipitik junto a Red Hulk en el taller" fetchpriority="high" width="1440" height="1920"></div><div class="hero-content wrap"><p class="eyebrow">Taller de escultura</p><h1>LO IMPOSIBLE<br><span>TOMA FORMA.</span></h1><p class="hero-description">Transformamos ideas en piezas<br>que impresionan.</p><a class="button" href="/proyectos/">Explorar proyectos</a></div><p class="hero-credit">Red Hulk / Escultura y acabado</p></section><div class="statement">IDEAS GRANDES. PIEZAS REALES.</div><section class="wrap atelier" id="taller"><div>${label('01','El taller')}<h2>OFICIO EN<br>CADA DETALLE.</h2><p>Personajes, objetos y espacios.<br>Cada pieza nace de una idea<br>y cobra vida en el taller.</p><a class="text-link" href="/equipo/">Conoce al equipo</a></div><a class="atelier-image" href="/proyectos/tron/"><img src="${projects.find(p=>p.slug==='tron').feature}" alt="Light Cycle de Tron en un stand promocional" width="1000" height="750" loading="lazy"><span>Tron · Light Cycle / Ver proyecto</span></a></section><section class="wrap selected" id="piezas">${label('02','Trabajos seleccionados')}<div class="section-heading"><h2>PIEZAS QUE HABLAN.</h2><a class="text-link" href="/proyectos/">Todos los proyectos</a></div><div class="project-grid">${['hulk','mufasa','pinocho','the-last-of-us','robin','tron'].map(slug=>projects.find(p=>p.slug===slug)).map(card).join('')}</div></section><section class="wrap services" id="servicios">${label('03','Lo que hacemos')}<p class="section-intro">De la primera idea a la pieza terminada.</p>${services.map(([title,text],i)=>`<details ${i===0?'open':''}><summary><span class="service-number">0${i+1}</span><h3>${title}</h3><span class="plus" aria-hidden="true">+</span></summary><p>${text}</p></details>`).join('')}</section><section class="wrap process">${label('04','Del concepto a la realidad')}<h2>CADA IDEA TIENE UN PROCESO.</h2><div class="process-grid">${[['Ideamos','Escuchamos tu visión.'],['Esculpimos','Damos forma al detalle.'],['Instalamos','Llevamos la pieza a su espacio.']].map(([title,text],i)=>`<div><p class="process-number">0${i+1}</p><h3>${title}</h3><p>${text}</p></div>`).join('')}</div></section>${contact}`;
function write(route,html){const dir=path.join(out,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html)}
write('',page('Lo imposible toma forma','Escultura monumental, personajes, props y escenografía. Descubre las piezas y las personas del taller Pipitik.','/',home));
write('proyectos',page('Proyectos','Una selección de esculturas, criaturas, props y espacios realizados por el taller Pipitik.','/proyectos/',`<section class="wrap page-intro">${label('Portafolio','Proyectos')}<h1>PIEZAS QUE<br><span>HABLAN.</span></h1><div class="intro-bottom"><p>Personajes, objetos y espacios.<br>Una mirada al trabajo del taller.</p><span class="count">${projects.length} proyectos</span></div></section><section class="wrap catalog"><div class="project-grid">${projects.map(card).join('')}</div></section>${contact}`,'proyectos'));
projects.forEach((p,i)=>{const next=projects[(i+1)%projects.length];const route=`/proyectos/${p.slug}/`;write(`proyectos/${p.slug}`,page(p.title,p.description,route,`<section class="project-intro wrap"><a class="breadcrumb" href="/proyectos/">Todos los proyectos</a><p class="eyebrow">${p.category}</p><h1>${p.title}</h1></section><figure class="project-hero"><img src="${p.hero}" alt="${p.title}, pieza terminada" width="1920" height="1440" fetchpriority="high" style="object-position:${p.position||'50% 50%'}"><figcaption>${p.title} / Pipitik</figcaption></figure><section class="wrap project-description"><p class="eyebrow">La pieza</p><p>${p.description}</p></section>${p.groups.map((g,j)=>`<section class="wrap project-process">${label(String(j+1).padStart(2,'0'),g.title)}<div class="section-heading"><h2>${g.title}</h2><p>${g.text}</p></div><div class="gallery">${g.images.map((id,k)=>`<button class="gallery-item" data-photo="${asset(id)}" data-caption="${escape(p.title+' · '+g.title+' / '+(k+1))}" aria-label="Ampliar fotografía ${k+1} de ${g.title}"><img src="${asset(id)}" alt="${g.title}, detalle ${k+1}" width="1000" height="1000" loading="lazy"><span>Ampliar fotografía</span></button>`).join('')}</div></section>`).join('')}<section class="wrap next-project"><p class="eyebrow">Siguiente proyecto</p><a href="/proyectos/${next.slug}/">${next.title}</a></section>${contact}`,'proyectos',p.hero));});
write('equipo',page('El taller','Conoce a las personas detrás de Pipitik: dirección, escultura, diseño y decoración.','/equipo/',`<section class="wrap page-intro">${label('El taller','Nuestro equipo')}<h1>LAS MANOS<br><span>DETRÁS DE LA IDEA.</span></h1><p class="about-intro">Somos un taller de escultura. Reunimos diseño, producción y oficio para transformar una idea en una pieza que se puede tocar, recorrer y recordar.</p></section><div class="team-banner"><img src="${studioPhoto}" alt="Equipo de Pipitik junto a Red Hulk en el taller" width="1920" height="1440" loading="lazy"></div><section class="wrap team-section">${label('01','Las personas')}<h2>EL EQUIPO.</h2><div class="team-grid">${team.map((t,i)=>`<article class="team-member"><div class="portrait">${t.portrait?`<img src="${t.portrait}" alt="Retrato de ${t.name}" width="750" height="1000" loading="lazy">`:`<div class="portrait-monogram" aria-hidden="true">${escape(t.initials||t.name.split(" ").map(n=>n[0]).join(""))}</div>`}<span>0${i+1}</span></div><p class="eyebrow">${t.role}</p><h3>${t.name}</h3><p class="bio">${t.bio}</p></article>`).join('')}</div></section><section class="wrap about-note">${label('02','Lo que nos mueve')}<h2>FORMA. TEXTURA.<br>CARÁCTER.</h2><p>La escala puede cambiar. El cuidado por el detalle, siempre está presente. Trabajamos cada pieza desde el concepto hasta su acabado e instalación.</p></section>${contact}`,'equipo'));
fs.writeFileSync(path.join(out,'404.html'),page('Página no encontrada','Explora el trabajo de Pipitik.','/404/',`<section class="wrap page-intro"><p class="eyebrow">404</p><h1>VOLVAMOS<br>AL TALLER.</h1><p>Esta página no está disponible.</p><a class="button" href="/proyectos/">Explorar proyectos</a></section>`));
const routes=['/','/proyectos/','/equipo/',...projects.map(p=>`/proyectos/${p.slug}/`)];fs.writeFileSync(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>https://pipitik.netlify.app${r}</loc></url>`).join('')}</urlset>`);fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://pipitik.netlify.app/sitemap.xml\n');
console.log(`Built ${routes.length} pages, ${projects.length} projects.`);

// Unlinked responsive review surfaces, generated only for Netlify previews.
if(process.env.CONTEXT==='deploy-preview'){
 for(const width of [360,390,700,1440]){
  write(`_preview-checks/${width}`,`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><title>Revisión ${width}px</title></head><body style="margin:0;background:#303030"><iframe title="Pipitik a ${width}px" src="/" style="display:block;width:${width}px;height:${width<=700?780:900}px;border:0"></iframe></body></html>`);
 }
}
