const img=id=>`/assets/${id}.webp`;
export const projects=[
{slug:'hulk',title:'Hulk & Capitán América',short:'Hulk',category:'Personajes y réplicas',hero:'/assets/hulk-in-situ.webp',fit:'contain',position:'50% 40%',description:'Fuerza, escala y detalle. Un proyecto que reúne a Red Hulk, Hulk verde y el escudo del Capitán América: del volumen de los personajes al acabado de sus superficies.',groups:[{title:'Red Hulk',text:'Escultura, construcción y acabado de un personaje a gran escala.',images:['1Iax9uq3S8ztbmqFBPPNfzx9dUI91Y4fT','1L9H2WgB6bWHX-lG1a9WH_4iN6hY0iEGn']},{title:'Hulk verde',text:'Renovación de superficies, color y detalle.',images:['1mJI5rQ6olwnvXC0hj0Hm8Xd_8JySnkPY','1R9XOTR01UJtbipq2HVDdQX4YKFyh5JCa','1IsxchNy7ILABS7g_ntcp1nZzj9Nnl-OF']},{title:'El escudo',text:'El escudo del Capitán América y sus réplicas en resina.',images:['19Sg5110J9lTIBx-YK09vzMVjmbkVRLjZ','11KXLcBTCnsPM1dYB52VTTSZb_I_vb6w2','11LSyPPqKWMyiwhEMX2QJ-dqUi2mtq50G']}]},
{slug:'alien',title:'Alien',short:'Alien',category:'Criaturas y escenografía',hero:img('1Hi2mgoz0gudYQgXtTkRlHJk8krgWv_SR'),description:'Un universo de superficies orgánicas y arquitectura. La criatura de Alien: Romulus, su huevo y el pasillo de Alien se reúnen en una sola exploración de escultura y espacio.',groups:[{title:'La criatura',text:'Volumen, textura y acabado para una presencia que se siente real.',images:['1YYAMTEkF8P5SIcWydQ77XPp9pSBNtbMg','1t6k2caioDjDlZ9O0ZdGw07Vir0ANHG9G']},{title:'El huevo',text:'Del modelado de la superficie a los detalles de la piel.',images:['1LeesVg0MwxXTixwDNJ8__q651ez0UkK7','1cXsIjiZW-XbeLxTbYd8KfXDhZMF3O8wC','1mzhy6C0mNzHRyeE_cJ2dQ-YNhovg4gT8']},{title:'El pasillo',text:'Escenografía que lleva el universo de Alien al espacio físico.',images:['1pbY_7btD6adHPSXx01i_aMun06PDhQ69']}]},
{slug:'pinocho',title:'Pinocho',category:'Escultura monumental',hero:'/assets/pinocho-hero-cinema-ai.webp',fit:'contain',description:'Una mirada familiar llevada a escala monumental. Un busto de Pinocho para la película de Guillermo del Toro, trabajado desde el volumen inicial hasta el detalle del acabado.',groups:[{title:'Dentro del taller',text:'Modelado, textura y pintura: cada etapa conserva el carácter del personaje.',images:['18tbOHqQTWg1XTVCxFr6XcAlxQcrQH-s5','1mFtJDfzQ3tqlzp6YTjkvAcgPjaI2ajN3','152aTpwhxgVn8WsqW5ZuZjNYbFd31kYIK']}]},
{slug:'the-last-of-us',title:'The Last of Us',category:'Criaturas y escenografía',hero:'/assets/the-last-of-us-hero-convention-ai.webp',fit:'contain',position:'50% 50%',description:'Una criatura que se funde con su entorno. El relieve, las texturas y el crecimiento orgánico construyen una presencia física para el universo de The Last of Us.',groups:[{title:'Textura y presencia',text:'Detalle del personaje y del entorno escultórico.',images:['17GAuO2KRTw5Ngf2uOuRLyIujAdpt9SIp','1gFfDH3OodTx-LdKF53xPLZft4wkTkzP7']}]},
{slug:'robin',fit:'contain',title:'Robin',category:'Personajes y réplicas',hero:'/assets/robin-hero-alex.webp',description:'Robin, a escala real. Una escultura para Titans que concentra el trabajo en la silueta, la expresión y los detalles del traje.',groups:[{title:'Del modelado al personaje',text:'Anatomía, vestuario y detalle de superficie.',images:['1stUzak_g-K2RW4kg6Nsb0LFMQ1LtyMdW','1KC4hgKPbLpmp5G731JFXyqZNgsW88sEu','1yjphE58EAcZDSqVH7A6XqPIGYHy8elXS']}]},
{slug:'tron',title:'Tron · Light Cycle',short:'Tron',category:'Props y utilería',hero:img('1lbC1p70I5sYoJ44mgkrqQNZcMu9KeB9t'),feature:img('1jdeAc_-WF9Yh44oVDpSCc2reavp5YEDc'),fit:'contain',description:'Una silueta que parece venir de otro mundo. La Light Cycle de Tron combina volumen, superficies y luz en una pieza construida para verse de cerca.',groups:[{title:'La pieza terminada',text:'Proporción, ensamblaje y presencia en exhibición.',images:['1ri7rmImX3lnmjniWs9t0mEv901WsRE5r','1jdeAc_-WF9Yh44oVDpSCc2reavp5YEDc']}]},
{slug:'mufasa',title:'Mufasa',category:'Personajes y réplicas',hero:'/assets/mufasa-hero-reforma-title-ai.webp',fit:'contain',description:'Mufasa sobre la roca, a escala monumental. Una escultura y un carro alegórico que llevan el carácter del personaje al Paseo de la Reforma, frente al Ángel de la Independencia.',groups:[{title:'Forma y acabado',text:'Del modelado al color y la textura final.',images:['1DoKFEKdMR-UKjpAOxvVoATHdM3FNPiwC','15y1oAt8lAyExryA9QbI71Ux2vNpzxJBR','1EywxcAXrTmxjHash40NKjiztGMEoHCZU']}]},
{slug:'proximus-caesar',title:'Próximus César',category:'Personajes y réplicas',hero:'/assets/proximus-caesar-hero-location-ai.webp',description:'Una figura con peso propio. Proximus Caesar y su trono se construyen a través del gesto, el vestuario y la riqueza de sus superficies.',groups:[{title:'El trabajo detrás de la pieza',text:'Detalle de escultura y construcción del trono.',images:['1T-wKaYcIBZRaWl6PtQwhYtpUSagOkYeU','1O6G_mK0wLhg1E598EQmhL6DtSOrwgqkO','1vcwpQ5iP5RnDXXjbioyUysyg4l6rzkoc']}]},
{slug:'spiderman',title:'Spider-Man',category:'Personajes y réplicas',hero:'/assets/spiderman-hero-alex.webp',description:'La energía del personaje en una pieza física. Un trabajo de proporción, estructura y superficie que lleva a Spider-Man del taller a la exhibición.',groups:[{title:'Construcción y detalle',text:'Modelado, traje y acabado del personaje.',images:['1pjYALH5ZkJhyKp6VImpzBEt4cZMkyQdU','1_6cjxkdaEPVi3JAV9kfQL3TPHviy_Sll','1RkN8KccZBcEBdIcQL5ZuIqsg1pZmAOmw']}]},
{slug:'demogorgon',title:'Demogorgon',category:'Criaturas',hero:'/assets/demogorgon-hero-ai.webp',fit:'contain',description:'La criatura de Stranger Things, construida desde su silueta hasta la textura de cada superficie. Un personaje donde el gesto y el detalle son inseparables.',groups:[{title:'Anatomía de una criatura',text:'Exploración de forma, textura y acabado.',images:['1JrZIIFUXoTyY2Yg8uQBc03bPantRSeqo','1fm5Mw3s9fJz3SEdG07PPWmbBwT8WSdIX','1s8HnyGkSI5z6W6VMWbRK-FCZrF9dgIhu']}]},
{slug:'ballena',title:'Ballena monumental',category:'Escultura monumental',hero:'/assets/ballena-hero-ai.webp',fit:'contain',description:'Doce metros de escultura para el universo de The Boys, presentada en CCXP. Una ballena construida para transformar la escala de todo el espacio.',groups:[{title:'La escala del proyecto',text:'Del taller a la instalación y sus detalles de superficie.',images:['1-1viuy_lbnb1NXLkiZ4_U1xrN6ntxB70','173FQQn9iC6rthgA6EDcC9LnzOFgrHTIn','1gO7DvHqa3mq1OYRsqbtPYlUAVb94-oay']}]},
{slug:'blue-demon',title:'Blue Demon Jr.',category:'Personajes y réplicas',hero:'/assets/blue-demon-hero-ai.webp',fit:'contain',description:'Un ícono de la lucha libre, a escala real. La escultura de Blue Demon Jr. concentra el oficio en la expresión, la anatomía y la máscara.',groups:[{title:'La construcción de un ícono',text:'Modelado, pintura y pieza terminada.',images:['1ptmTGTjsLGNVm2-TkIh8a-xN1nFMPzLB','1IEtwKH8ICgJtWFkwSpXoRQBxSMmi3wkg','1X5zzHFTnnQJe2Ynt9FVbpPqrRoCdhhmc']}]},
{slug:'trono-de-hierro',title:'Trono de Hierro',category:'Props y escenografía',hero:'/assets/trono-de-hierro-hero-ai.webp',fit:'contain',description:'El Trono de Hierro para la segunda temporada de House of the Dragon, presentado en CCXP 2024. Una pieza definida por la acumulación, el ritmo y el detalle de sus espadas.',groups:[{title:'Del volumen al metal',text:'Estructura, modelado y acabado de superficie.',images:['1sZI9tOKVgb8trH-Ee7z2G4cwJPWRh4Sp','1w9avFh-I8ZA2dyzGCg3eTFNmtE_X9VIl','10ppZ0pHtq5hzX6jN5jQCmlk2yyQbJ_5n']}]},
{"slug": "checoneta", "title": "La Checoneta", "category": "Props y escenografía", "description": "Una carrocería construida para una experiencia promocional de Mercado Libre. Del volumen inicial al acabado amarillo y azul, la Checoneta reúne escultura, ensamblaje y pintura a gran escala.", "hero": "/assets/1vHSwFwftYf2yEEEAjWqVyoT3_y4gixHf.webp", "fit": "contain", "groups": []},
{"slug": "diorama-mamut", "title": "Diorama de mamut", "category": "Museografía y dioramas", "description": "Un mamut dentro de un paisaje escultórico. Anatomía, composición y trabajo de superficie se reúnen en una escena para exhibición museográfica.", "hero": "/assets/1fo66IlHthkTjch19BNAn8jRiwaHfLvr-.webp", "fit": "contain", "groups": []},
{"slug": "rancor", "title": "Rancor", "category": "Criaturas y escenografía", "description": "La criatura de Star Wars llevada a escala monumental. El volumen, los pliegues de la piel y el acabado construyen una presencia física para una exhibición de convención.", "hero": "/assets/1OFVOwLLhdjmHhEh0ul6tLZJdFGJ-ZNJW.webp", "fit": "contain", "groups": []}
];
export const studioPhoto='/assets/14rXf3nOjN4UfxEK78OU2vr5zWIweORDb.webp';
export const team=[
{name:'Ernesto Sarabia',role:'Dirección y producción',portrait:'/assets/ernesto.webp',bio:'Diseñador gráfico y director de arte. Su trayectoria reúne museografía, producción y dirección de estudio: trabajó como jefe de estudio en Rabia Studios y como productor y director de arte en Goma Producciones. Desde 2023 dirige Pipitik.'},
{name:'Lalo Moreno',role:'Escultura y modelado',portrait:'/assets/lalo.webp',bio:'Escultor dedicado a la creación de personajes, criaturas y piezas a escala. Su trabajo reúne modelado, anatomía, texturas, moldes y réplicas, del primer volumen al acabado final.'},
{name:'Ariadne Orozco',role:'Escultura y diseño',portrait:'/assets/ariadne.webp',bio:'Escultora y diseñadora con experiencia en bronce, resina, porcelana y cerámica. Su trabajo abarca retratos, personajes y obra original. Ha realizado piezas para Disney, Warner Brothers y colecciones privadas, y ha dirigido el taller de Morton Porcelana.'},
{name:'Gonzalo Lugo',role:'Jefe de decoración',portrait:'/assets/gonzalo.webp',bio:'Artista de pintura y escultura. Su práctica reúne trabajo de superficie, color y volumen; en el taller, su oficio de decoración da a las piezas su carácter y acabado final.'},
{name:'Joel',role:'Equipo del taller',portrait:'/assets/joel.webp',bio:'Joel forma parte del equipo de Pipitik y del trabajo cotidiano del taller.'}
];
export const services=[['Escultura monumental','Piezas de gran formato para exhibiciones, eventos y espacios. Trabajamos el volumen, la estructura y el acabado como un solo proyecto.'],['Personajes y réplicas','Personajes a escala, bustos y réplicas. Del modelado a la pintura, cada decisión sostiene la expresión y el carácter de la pieza.'],['Props y utilería','Objetos que cuentan una historia. Construimos elementos físicos para producciones y experiencias, con atención al uso y al detalle.'],['Escenografía','Espacios y elementos que llevan una idea al mundo real. Integramos construcción, textura y acabado en el entorno.']];
